
= Model Description

== Print Name

Modular TableClip System (with sources!)

== Summary

Do you have table so cluttered you don't see the color of the desk? TableClip to the rescue!

== Description

Do you have table so cluttered you don't see the color of the desk? *TableClip* to the rescue! ;)

Jokes aside, some time ago I've got inspired by the https://www.thingiverse.com/thing:2892387 and thought that this could be extended to other useful things and also improved.

So I designed modular system that is divided to parts. The table clip itsef and various modules that can be attached to the clip through lock mechanism.

.Available modules
* cable holder
* pen and paper holder
* headphones holder

The base modules are currently in 20mm and 30mm width. But it is very simple to add more.

*BUT* the best thing about it is that I'm sharing the sources (https://github.com/MikiGrit/table_clip). So everybody can design new modules that can be attached to the base module.

If you do not want to design new modules in the OpenSCAD (for which the sources are), you can use just the key object (`_key.stl`) and add it to anything you design in program of your choice. The key and the lock themselves are designed in a way that allows for two things:

. It is not necessary to print the key in full height. The connected module still stays on top (see headphones holder for example).
. Key does not have to be printed from the bed, it is fully capable of printing in the middle of the print. The modules themselves can therefore extend below the table (see pencil holder for example).

Link to the sources: https://github.com/MikiGrit/table_clip

=== Print instructions

You should print one base module (`base_*.stl`), two screws and connecting module of your choice.

Everything should be printable without supports. Tested with 0.2mm layer.
